on:
  workflow_dispatch:
  push:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          echo Hello... we are preparing the environment.
          sleep 5
          exit 0

  Deploy:
    if: always()
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Init fmt and validate
        run: |
          echo terraform init, fmt and validate
          sleep 10
          exit 0
      - name: Terraform apply
        run: |
          echo terraform apply
          sleep 15
  
  Release:
    needs: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Releasing
        run: |
          echo So... whats up next?
          delay 3